import type { Product, Category } from '@/types/product';

// Sample data to use when Sanity is empty or not configured
export const sampleCategories: Category[] = [
  { id: 'cat-1', slug: 'home-decor', title: 'Home Decor', sort_order: 1, created_at: new Date().toISOString() },
  { id: 'cat-2', slug: 'kitchen', title: 'Kitchen', sort_order: 2, created_at: new Date().toISOString() },
  { id: 'cat-3', slug: 'bath', title: 'Bath', sort_order: 3, created_at: new Date().toISOString() },
  { id: 'cat-4', slug: 'lighting', title: 'Lighting', sort_order: 4, created_at: new Date().toISOString() },
];

export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    slug: 'ceramic-vase',
    title: 'Ceramic Vase',
    description: 'A beautiful handcrafted ceramic vase perfect for any room.',
    images: ['/src/assets/products/ceramic-vase.jpg'],
    price_cents: 4500,
    discount_percent: 0,
    out_of_stock: false,
    category: 'home-decor',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    slug: 'ceramic-mug',
    title: 'Ceramic Mug',
    description: 'Elegant ceramic mug for your morning coffee.',
    images: ['/src/assets/products/ceramic-mug.jpg'],
    price_cents: 2500,
    discount_percent: 10,
    out_of_stock: false,
    category: 'kitchen',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    slug: 'bath-towels',
    title: 'Luxury Bath Towels',
    description: 'Soft and absorbent bath towels made from premium cotton.',
    images: ['/src/assets/products/bath-towels.jpg'],
    price_cents: 3500,
    discount_percent: 0,
    out_of_stock: false,
    category: 'bath',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    slug: 'desk-lamp',
    title: 'Modern Desk Lamp',
    description: 'Sleek desk lamp with adjustable brightness.',
    images: ['/src/assets/products/desk-lamp.jpg'],
    price_cents: 7900,
    discount_percent: 15,
    out_of_stock: false,
    category: 'lighting',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    slug: 'linen-throw',
    title: 'Linen Throw Blanket',
    description: 'Cozy linen throw blanket for your living room.',
    images: ['/src/assets/products/linen-throw.jpg'],
    price_cents: 5900,
    discount_percent: 0,
    out_of_stock: false,
    category: 'home-decor',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    slug: 'scented-candle',
    title: 'Scented Candle',
    description: 'Hand-poured soy candle with natural fragrances.',
    images: ['/src/assets/products/scented-candle.jpg'],
    price_cents: 2800,
    discount_percent: 0,
    out_of_stock: false,
    category: 'home-decor',
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    slug: 'wooden-board',
    title: 'Wooden Cutting Board',
    description: 'Durable wooden cutting board for your kitchen.',
    images: ['/src/assets/products/wooden-board.jpg'],
    price_cents: 4200,
    discount_percent: 20,
    out_of_stock: false,
    category: 'kitchen',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    slug: 'room-spray',
    title: 'Room Spray',
    description: 'Refreshing room spray with calming lavender scent.',
    images: ['/src/assets/products/room-spray.jpg'],
    price_cents: 1800,
    discount_percent: 0,
    out_of_stock: true,
    category: 'home-decor',
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
