// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta as any).env.VITE_SUPABASE_URL || "https://prdihsdgnmamgsztewbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZGloc2Rnbm1hbWdzenRld2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MjU4OTIsImV4cCI6MjA4MjAwMTg5Mn0.CKrcFlybVAIpXR_2wTma2kt6wX4oVbpUD3iPVo37Nek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});